/**
 * Pro league rules, rounded to the 2025-26 NBA CBA.
 * A college mod should replace this object (no cap, different roster and schedule)
 * instead of hardcoding numbers in the sim.
 */
export const NBA_RULES = {
  SALARY_CAP: 140_600_000,
  LUXURY_TAX: 170_814_000,
  FIRST_APRON: 178_132_000,
  SECOND_APRON: 188_910_000,
  MINIMUM_SALARY: 1_150_000,
  MAX_SALARY: 60_000_000,
  MLE: 12_800_000,
  TAXPAYER_MLE: 5_000_000,
  BAE: 4_700_000,
  ROSTER_MIN: 14,
  ROSTER_MAX: 15,
  /** Standard roster plus one pick per draft round, until opening day. */
  OFFSEASON_ROSTER_MAX: 17,
  DRAFT_ROUNDS: 2,
  SCOUTING_TOKENS: 8,
  PLAYOFF_SPOTS_PER_CONFERENCE: 4,
  SCHEMA_VERSION: 2
} as const

export const CBA_CONSTANTS = {
  SALARY_CAP: NBA_RULES.SALARY_CAP,
  LUXURY_TAX: NBA_RULES.LUXURY_TAX,
  FIRST_APRON: NBA_RULES.FIRST_APRON,
  SECOND_APRON: NBA_RULES.SECOND_APRON,
  MINIMUM_SALARY: NBA_RULES.MINIMUM_SALARY,
  MAX_SALARY: NBA_RULES.MAX_SALARY,
  MLE: NBA_RULES.MLE,
  TAXPAYER_MLE: NBA_RULES.TAXPAYER_MLE,
  BAE: NBA_RULES.BAE,
  ROSTER_MIN: NBA_RULES.ROSTER_MIN,
  ROSTER_MAX: NBA_RULES.ROSTER_MAX,
  ROOKIE_SCALE_BASE: 3_200_000
}
